### PR TITLE
Fix/warn on leave

### LINKED ISSUE #198: Warn user if trying to leave form with inputted data
The form should give a warning dialog if the user tries to either a) change tabs in the UI or b) close the browser tab/window after data has been filled in to any of the form fields.

### PR DESCRIPTION
**Pull request by jonraem**
Show prompt if user is leaving with unsaved changes.

Fixes #198.

### CODE REVIEW

**Comment by Rikuoja** [comment]
Might be a problem with my rebase though, perhaps a proper rebase will fix things up? =)

File: src/views/Editor/index.js [hunk 1]
```diff
@@ -66,6 +74,35 @@ var EditorPage = React.createClass({
...
     },
 
+    componentWillUnmount() {
+        window.removeEventListener("beforeunload", this.handler)
+        this.props.dispatch(setValidationErrors({}))
+    },
+
+    routerWillLeave(nextLocation) {
+        if (this.state.isDirty) {
+            return 'Changes that you have made may not be saved.\n\nAre you sure you want to leave?'
```
Comment (Rikuoja) [inline src/views/Editor/index.js]: This should be in Finnish, as the form is currently in Finnish only. No internationalization support for the strings needed at the moment.
