### PR TITLE
Fix/add description

### LINKED ISSUE #187: Add additional text to description if Palvelukeskuskortti-target audience selected
In event submission form: if the Palvelukeskuskortti-target audience is selected as target audience (Kohderyhmä), add the following text to the beginning of the event description ("fi" only), when the event is written to the API:

"Tapahtuma on tarkoitettu vain eläkeläisille ja työttömille, joilla on <a href="http://www.hel.fi/www/sote/fi/palvelut/palvelukuvaus?id=3252" target="_blank">palvelukeskuskortti</a>.\n\n

### PR DESCRIPTION
**Pull request by jonraem**
Add description to "palvelukeskuskortti". Add HTML support for description text field.

Fixes #187.

### CODE REVIEW

File: src/actions/editor.js [hunk 1]
```diff
@@ -118,14 +119,37 @@ export function sendData(formValues, contentLanguages, user, updateExisting = fa
...
+          const desc = formValues.description[lang].replace(/\n\n/g, "</p><p>").replace(/\n/g, "<br/>")
+          if (desc.indexOf('<p>') === 0 && desc.substr(desc.length - 4) === '</p>') {
+              descriptionTexts[lang] = desc;
+          } else {
+              descriptionTexts[lang] = `<p>${desc}</p>`
+          }
+        }
+        // Check for 'palvelukeskuskortti' in audience
+        if (formValues) {
+            if (formValues.audience && includes(formValues.audience, "https://api.hel.fi/linkedevents-test/v1/keyword/helsinki:aflfbat76e/")) {
```
Comment (Rikuoja) [inline src/actions/editor.js]: We shouldn't hardcode API addresses in the UI. This implementation doesn't work when testing with a local API, and neither will it work in production.

Comment (Rikuoja) [inline src/actions/editor.js]: The id `helsinki:aflfbat76e` is hardcoded in the backend (as it is a rather special case), so it is safe to use just that.

**Comment by jonraem** [comment]
Fixed.
