### PR TITLE
#435 - Fix validation with multiple languages

### LINKED ISSUE #435: Fix validation error with multiple languages
How to reproduce bug:

a) Save event in language 1 only.
b) Edit event, add language 2 to form. 
c) Remove content from (some of) language 1's multilingual fields.
d) Remove language 1 from form (from This event will be presented in following languages. -menu)
e) Save event.

RESULT: Language 1 multilingual fiels data is saved as "null" to API, which should not be allowed. This can result in an event with e.g. a langua 1 description but no language 1 name.

The bug can also result in data being stored (language 1) even though the user wished to remove that data.

Fix validation so that previously held language data (language 1) in multilingual fields is wiped from API completely. The above case should result in an event with language 2 data only.

EDIT: Deselecting all languages on the form is currently allowed. This creates further issues. Change the form's behaviour so that a minimum of one language selection is always required.

### PR DESCRIPTION
**Pull request by niglu1**
This PR fixes #435 

- Fix issue where the values of deselected languages weren’t nullified
- Multiple language fields for offers are now nullified, they weren’t before
- Validation is now run after the multiple language field values have been nullified. This fixes the issue where invalid values for deselected languages triggered validation warnings
- Unselecting all languages is no longer possible

### CODE REVIEW

File: src/validation/validationRules.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 
 import moment from 'moment'
-import {includes, every} from 'lodash';
+import {includes, every, isNull} from 'lodash';
```
Comment (Rikuoja) [inline src/validation/validationRules.js]: Why are we adding isNull in the validators? What happens when e.g. data from the API has some null fields, it seems with this validator we are allowing null fields to go back into the API?

Especially since now we are nullifying some fields, it would seem reselecting them would allow us to post null data in new languages in the API? Or am I missing something?

Comment (niglu1) [reply src/validation/validationRules.js]: > Why are we adding isNull in the validators? What happens when e.g. data from the API has some null fields, it seems with this validator we are allowing null fields to go back into the API?

The validation of the form is now done after the values for deselected languages have been nullified. Those nullified values will be passed to the validator, hence the added null check. This was done to fix the issue where invalid values for deselected languages triggered validation warnings.

**Example:**
1. fi and sv are selected as the languages.
2. The user enters a _valid_ value for fi and an _invalid_ value for sv to the homepage url field.
3. The user then unselects sv, so that fi remains the only selected language.
4. The user saves the (seemingly valid) form. (Let's assume that the rest of the fields are valid)

This would result in a validation popup being shown for the homepage url, as the unselected language values hadn’t been cleared yet. The values for languages are _not_ cleared when a user un- or reselects a language, it's done only when the save button is pressed.

> Especially since now we are nullifying some fields, it would seem reselecting them would allow us to post null data in new languages in the API? Or am I missing something?

I'm not quite sure I understand.

File: src/actions/editor.js [hunk 2]
```diff
@@ -175,36 +175,51 @@ const prepareFormValues = (formValues, contentLanguages, user, updateExisting, p
...
-        }
-    }
-
     // Format descriptions to HTML
-    const descriptionTexts = formValues.description
-    for (const lang in formValues.description) {
-        if (formValues.description[lang]) {
-            const desc = formValues.description[lang].replace(/\n\n/g, '</p><p>').replace(/\n/g, '<br/>').replace(/&/g, '&amp;')
-            if (desc.indexOf('<p>') === 0 && desc.substr(desc.length - 4) === '</p>') {
+    const descriptionTexts = multiLanguageValues.description || formValues.description
```
[the remark this answers is not in the document]
Comment (niglu1) [reply src/actions/editor.js]: Good catch, I'll change that.

File: src/validation/validationRules.js (hunk 1 above)
Comment (Rikuoja) [reply src/validation/validationRules.js]: Okay, I believe this is OK in the current API implementation. Because this will result in `null` values being posted to the API, as opposed to missing dictionary keys.

The current API spec doesn't tell what should happen if the UI posts `null` in a specific language field. Luckily, the internal implementation is such that `null` language fields are not returned by the API in GET, so we are fine.

Earlier, we had issues with the API actually returning `null` for missing languages, if `null` was POSTed for a specific language. Currently, it should leave them out, though.

Example:

1) the UI POST contains an object 
```
{
`fi`: `text`,
`sv`: null
}
```

2) GETting the same resource will return an object
```
{
`fi`: `text`
}
```

with the null field missing. So this should be fine.

Comment (Rikuoja) [reply src/validation/validationRules.js]: So, my question was just whether the UI should POST any nullified languages at all, or not. But most likely the results are identical in both cases.

Comment (Rikuoja) [reply src/validation/validationRules.js]: So, if the UI is fine with both missing language keys and null valued language keys (and behaves identically in both cases), this is fine.
